// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:main.MonType):Promise<string>;

export function ListeType():Promise<Array<main.MonType>>;
